// ------------------------------------------------------------------------------
//  <autogenerated>
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("Castle.ActiveRecord")]
[assembly: System.Reflection.AssemblyProduct("Castle.ActiveRecord")]
